[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "convert"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.7"

[tool.setuptools.packages.find]
where = ["lib"]

[tool.setuptools.package-data]
convert = ["*.dll", "*.so"]
